### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{yodgorbek.komilov.musobaqayangiliklari/yodgorbek.komilov.musobaqayangiliklari.ui.SliderActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.denzcoskun.imageslider.ImageSlider.setImageList(java.util.List, boolean)' on a null object reference

### ISSUE THREAD

**Issue by kyodgorbek** [denzcoskun/ImageSlideshow#26]
I am developing a news app and I am using your library but when I run the application I am getting the following exception

java.lang.RuntimeException: Unable to start activity ComponentInfo{yodgorbek.komilov.musobaqayangiliklari/yodgorbek.komilov.musobaqayangiliklari.ui.SliderActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.denzcoskun.imageslider.ImageSlider.setImageList(java.util.List, boolean)' on a null object reference
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2976)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3113)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:113)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:71)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1858)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:201)
 at android.app.ActivityThread.main(ActivityThread.java:6820)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:922)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.denzcoskun.imageslider.ImageSlider.setImageList(java.util.List, boolean)' on a null object reference
 at com.denzcoskun.imageslider.ImageSlider.setImageList$default(ImageSlider.kt:59)
 at yodgorbek.komilov.musobaqayangiliklari.ui.SliderActivity.onCreate(SliderActivity.kt:32)
 at android.app.Activity.performCreate(Activity.java:7224)
 at android.app.Activity.performCreate(Activity.java:7213)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2956)
 ... 11 more

below my SliderActivity.kt

class SliderActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_slider)
        val imageSlider = findViewById<ImageSlider>(R.id.image_slider)
        val imageList = ArrayList<SlideModel>()
        imageList.add(
            SlideModel(R.drawable.news, "Follow live news")
        )
        imageList.add(
            SlideModel(R.drawable.news_slider, "Follow live news")
        )
        imageList.add(
            SlideModel(R.drawable.news, "Follow live news")
        )

        imageSlider.setImageList(imageList, true)

    }
}

below my activity_slider.xml
```

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.denzcoskun.imageslider.ImageSlider
        android:id="@+id/image_slider"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />


</LinearLayout>
```
I am doing exactly as suggested in read me file

**Comment by kyodgorbek** [comment]
fixed issue by updating the build toolversion
